apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
    tier: frontend
  name: web-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
        tier: frontend
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: eu.gcr.io/chariots-poc/ml_back/cahriots-server:latest
          name: flask
          ports:
            - containerPort: 5000
status: {}

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  creationTimestamp: null
#  labels:
#    app: flask
#    tier: frontend
#  name: web-flask
#spec:
#  ports:
#  - port: 5000
#    protocol: TCP
#    targetPort: 5000
#  selector:
#    app: flask
#    tier: frontend
#  type: NodePort
#status:
#  loadBalancer: {}