apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: predictions
  labels:
    app: scripts
    role: script
    tier: job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: chariots-scripts
              image: eu.gcr.io/chariots-poc/ml_back/chariots-scripts:latest
              command: ["python3", "make_predictions.py"]
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: password
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: dbname
                - name: DB_HOST
                  value: "sql-proxy-service"
          restartPolicy: Never
